pipeline {
    agent any
    stages {
        stage('checkout') { # checkout code from git
            steps {
                sh 'git clone ' + env.GIT_URL
            }
        }
        stage('install') { # install dependencies
            steps {
                sh 'npm install'
            }
        }
        stage('test') { # run tests
            steps {
                sh 'npm test'
            }
        }
        stage('build') { # build the project
            steps {
                sh 'npm run build'
            }
        }
    }
}